### ISSUE TITLE
Broken typescript generated, when using dots in method names

### ISSUE THREAD

**Issue by ivankhm** [open-rpc/generator#619]
**Describe the bug**
Incorrect methods names when using typescript client generator on a schema that has dots in method names.

**To Reproduce**
1. run `npm install -g @open-rpc/generator`
2. Create file `openrpc.json` with the following content using dots in method names:
```JSON
{
  "openrpc": "1.0.0-rc1",
  "info": {
    "title": "test",
    "version": "1.0.0"
  },
  "methods": [
    {
      "name": "foo.bar",
      "summary": "test",
      "params": [],
      "result": {
        "name": "fooBarResult",
        "schema": {
          "type": "object"
        }
      }
    }
  ]
}
```

3. run `open-rpc-generator generate -t client -l typescript -n test-d ./openrpc.json -o ./generated`
4. go to `./generated/client/typescript/src/index.ts`
5. See typescript error on line 153 due to incorrect syntax.
```javascript
  public foo.bar: FooBar = (...params) => {
    return this.request("foo.bar", params);
  }
```

**Expected behavior**
Dot replaced with '_' (or somehow removed, like `fooBar`) for typescript method name:
```javascript
  public foo_bar: FooBar = (...params) => {
    return this.request("foo.bar", params);
  }
```

**Desktop**
 - OS: Windows 10
 - `@open-rpc/generator` version `^1.18.11`

**Comment by LaysDragon** [comment]
I encounter the same problem just in a hour, I use zenrpc to build server side rpc server. And I try to convert its smd schema into openrpc and generate client from the converted one. But the problem is zenrpc have the concept called namespace, which just add namespace in from of the method name. And cursed the openrpc generator generated invalid typescript like this.
```ts
/**
   * 
   */
  // tslint:disable-next-line:max-line-length
  public user.Login: UserLogin = (...params) => {
    return this.request("user.Login", params);
  }
```

**Comment by ivankhm** [comment]
I figured out a workaround - I just wrote a post-generation script, that replaces dots with underscores in the final file. Here is the function, it's quite naive, but works:
```javascript
import { readJson, readFile, writeFile } from "fs-extra";
import { OpenrpcDocument as OpenRPC, MethodObject } from "@open-rpc/meta-schema";

const fixMethodsWithDots = async (openrpcFilePath: string, generatedFilePath: string, finalOutputPath: string) => {
  const openrpcDocument: OpenRPC = await readJson(openrpcFilePath);
  let generatedFileContents: string = await readFile(generatedFilePath, "utf-8");
  const methodNames: string[] = openrpcDocument.methods.map(method => (<MethodObject>method).name);

  const methodNamesReplacements: [string, string][] = methodNames.map(methodName => (["public "+methodName, "public "+methodName.replace(".", "_")]));

  for (const [withDot, withUnderscore] of methodNamesReplacements) {
    generatedFileContents = generatedFileContents.replace(withDot, withUnderscore);
  }

  await writeFile(finalOutputPath, generatedFileContents);
}
```

I'll keep it for now, so it just works, but I'm really looking forward to this bugfix.

**Comment by LaysDragon** [comment]
I modify the master to generate code I want. https://github.com/Laysi/open-rpc-generator
It would generated nested class to move the method into its own namespace class. and add some tweak to made it working under angular environment and ci. Compare to openapi generator it still lack some custom field for further usage in template.

**Comment by BelfordZ** [comment]
Thanks for the issue and nice catch.

Im happy to implement or take a PR for the initially suggested fix. The nesting fix is very interesting, and I don't want to completely dismiss it, but its quite a bit bigger of a change. Great work on creating a fork to implement it though - really nice!

Let me know if you wanna make a PR, otherwise Ill get to it sooner or later :)

**Comment by LaysDragon** [comment]
> Thanks for the issue and nice catch.
> 
> Im happy to implement or take a PR for the initially suggested fix. The nesting fix is very interesting, and I don't want to completely dismiss it, but its quite a bit bigger of a change. Great work on creating a fork to implement it though - really nice!
> 
> comment if you want to make a PR, otherwise ill put one together soon.

Thanks, I didn't made PR in first place because it seems out of the scope of jsonrpc spec have with namespace concept. But now I thought it would be fine to treat it as a extension in ts-client implement.
I glad to make a PR. :) I will remove these specified env tweak to made a new branch which have purer change.
